name: Laravel Deploy to Google Cloud

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, dom, fileinfo, mysql, gd
          coverage: xdebug

      - name: Copy .env for testing
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key for testing
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Tests
        run: php artisan test

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Fix directory permissions before deployment
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo chown -R ${{ secrets.SERVER_USER }}:${{ secrets.SERVER_USER }} /var/www/apisavitar"

      - name: Deploy to Google Cloud VM
        run: |
          rsync -avz --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            --exclude='storage/framework/cache/data' \
            --exclude='storage/framework/sessions' \
            --exclude='storage/framework/views' \
            --exclude='storage/logs' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/apisavitar/

      - name: Post-deployment tasks
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/apisavitar && \
            composer install --no-dev --optimize-autoloader && \
            php artisan optimize:clear && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache"

      - name: Fix permissions and restart Apache
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo chown -R www-data:www-data /var/www/apisavitar"
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo systemctl restart apache2"
